#!/usr/bin/env python3
"""
Diff the three files and print a table of results.
"""
import sys
from contextlib import ExitStack


def main(argv):
    if len(argv) != 4:
        print(f"USAGE: {argv[0]} REFERENCE CONTROL TEST")
        sys.exit(1)

    filenames = argv[1:]

    print("reference|control|test")
    print("-|-|-")

    with ExitStack() as stack:
        files = [stack.enter_context(open(name)) for name in filenames]
        lines = zip(*[map(lambda x: x.strip(), f.readlines()) for f in files])
        for reference, control, test in lines:
            if control == test:
                continue
            print(f"{reference}|{control}|{test}")


if __name__ == "__main__":
    main(sys.argv)
