#!/bin/bash

function print_title() {
    local title=$1
    echo ""
    echo "### $title"
    echo ""
}

function heck() { cargo run --quiet; }
function guava() { sbt run | grep -v "\["; }
function d2p() { g++ src/main.cpp -o target/d2p; ./target/d2p; }
function pyregexp() { src/main.py; }
function cases() { cat data/cases.txt; }
function unit() { cat data/unit.txt; }

function testcase() {
    local source=$1
    local prog_ref=$2
    local prog_test=$3

    res=$(scripts/format <("$source") <($source | $prog_ref) <($source | $prog_test))
    echo "$res"
    
    echo ""
    err=$(echo "$res" | wc -l)
    total=$($source | wc -l)
    echo "$((err-2)) mismatched out of $((total))"
}

function testsuite() {
    local title=$1
    local test=$2

    echo ""
    echo "## ${title}"
    print_title "alphanum_3"
    testcase scripts/alphanum_3 heck "$test"

    print_title "word_4"
    testcase scripts/word_4 heck "$test"

    print_title "cases"
    testcase cases heck "$test"

    print_title "unit"
    testcase unit heck "$test"
}

echo "# Test Results"
testsuite "Heck vs Python (regexp)" pyregexp
testsuite "Heck vs Direct2Parquet" d2p
testsuite "Heck vs CaseFormat" guava
